name: Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-22.04
    strategy:
      max-parallel: 4
      matrix:
        include:
          - python: 3.11.11
            django: 5.2.0
            djangorestframework: 3.16.0
          - python: 3.11.11
            django: 4.1.13
            djangorestframework: 3.14.0
          - python: 3.9.16
            django: 3.2.17
            djangorestframework: 3.13.0
          - python: 3.7.15
            django: 2.2.28
            djangorestframework: 3.9.4
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python ${{ matrix.python }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python }}
      - name: Install Dependencies
        run: >-
          python -m pip 
          install --upgrade 
          pip 
          'setuptools<58'
          wheel 
          flake8 
          'Django==${{ matrix.django }}'
          'djangorestframework==${{ matrix.djangorestframework }}'
      - name: Run Tests
        run: |
          ./runtests.sh
